services:
  app:
    build:
      context: .
    image: nextjs-dev
    ports:
      - "3000:3000"
    develop:
      watch:
        - action: sync
          path: ./
          target: /app
          ignore:
            - .git
            - node_modules
            - .next
